-- Discrepancy Analysis: Temas 5, 7, 8
-- Flag problematic questions for review
-- Total: 118 questions
-- Generated: 2026-02-09

-- Unique questions: 104

UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Contradicts Q756 on Art. 68.1 CE]' WHERE id = 207;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Contradicts Q207 on Art. 68.1 CE]' WHERE id = 756;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Contradicts Q1422 on Art. 69.4 CE]' WHERE id = 896;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Contradicts Q896 on Art. 69.4 CE]' WHERE id = 1422;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Contradicts Q1420 on Art. 91 CE]' WHERE id = 902;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Contradicts Q902 on Art. 91 CE]' WHERE id = 1420;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Contradicts Q778 on Art. 68.6 CE]' WHERE id = 901;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Contradicts Q901 on Art. 68.6 CE]' WHERE id = 778;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Contradicts Q1208 on Art. 26 LOPJ]' WHERE id = 1149;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Contradicts Q1149 on Art. 26 LOPJ]' WHERE id = 1208;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Contradicts Q1149 on Art. 26 LOPJ]' WHERE id = 851;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Contradicts Q1208 on Art. 26 LOPJ]' WHERE id = 1430;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Contradicts Q1208 on Art. 26 LOPJ]' WHERE id = 821;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Contradicts Q1267 on Art. 60.1 Ley 40/2015]' WHERE id = 968;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Contradicts Q968 on Art. 60.1 Ley 40/2015]' WHERE id = 1267;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Contradicts Q951 on Art. 44.1 Ley 2/2014]' WHERE id = 959;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Contradicts Q959 on Art. 44.1 Ley 2/2014]' WHERE id = 951;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 5 but cites law from Tema 6: Art. 2.2 LO 3/1980]' WHERE id = 770;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 5 but cites law from Tema 6: Art. 21.1 LO 3/1980]' WHERE id = 768;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 5 but cites law from Tema 6: Art. 19.2 LO 3/1980]' WHERE id = 771;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 5 but cites law from Tema 6: Art. 22.3 LO 3/1980]' WHERE id = 772;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 5 but cites law from Tema 6: Art. 11 LO 3/1980]' WHERE id = 786;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 5 but cites law from Tema 6: Art. 9 LO 3/1980]' WHERE id = 769;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 117.1 CE]' WHERE id = 214;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 122.3 CE]' WHERE id = 215;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Arts. 117.1 y 117.2 CE]' WHERE id = 216;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 122.2 CE]' WHERE id = 217;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 124.4 CE]' WHERE id = 218;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 122.3 CE]' WHERE id = 1142;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 122.3 CE]' WHERE id = 1371;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 122.3 CE]' WHERE id = 1150;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: TÃ­tulo VI CE]' WHERE id = 869;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 117.1 CE]' WHERE id = 871;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 122.3 CE]' WHERE id = 815;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 151.1 CE y Disp. Trans. 2Âª CE]' WHERE id = 1226;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 149.2 CE]' WHERE id = 1227;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 152.2 CE]' WHERE id = 1229;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 149.1.7Âª CE]' WHERE id = 1232;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 119 CE]' WHERE id = 1363;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 117.5 CE]' WHERE id = 849;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 141.1 CE]' WHERE id = 1392;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 152.1 CE]' WHERE id = 822;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 124.1 CE]' WHERE id = 861;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 122.3 CE]' WHERE id = 1429;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 120.1 CE]' WHERE id = 1155;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 118 CE]' WHERE id = 440;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 117.1 CE]' WHERE id = 1156;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 149.1.5 CE]' WHERE id = 1157;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 15 de la Ley 50/1997 establece que los Secretarios de Estado son nombrados y separados por Real Decreto del Consejo de Ministros, a propuesta del Presidente del Gobierno o del miembro del Gobierno a cuyo Departamento pertenezcan]' WHERE id = 447;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 124.2 CE]' WHERE id = 826;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 117.5 CE]' WHERE id = 850;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 122.3 CE]' WHERE id = 855;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 125 CE]' WHERE id = 1166;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: TÃ­tulo VI CE (Arts. 117-127)]' WHERE id = 870;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 117.1 CE]' WHERE id = 872;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 117.3 CE, Art. 117.5 CE]' WHERE id = 831;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 124.1 CE]' WHERE id = 1367;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 120.2 CE]' WHERE id = 1368;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 12 CE]' WHERE id = 1370;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 143.2 CE]' WHERE id = 1388;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 2 CE]' WHERE id = 1390;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 123.1 CE]' WHERE id = 860;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 119 CE]' WHERE id = 1154;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 117.5 CE]' WHERE id = 1158;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 120.3 CE]' WHERE id = 834;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 122.2 CE]' WHERE id = 853;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 124.4 CE]' WHERE id = 862;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 117.5 CE]' WHERE id = 1211;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 122.2 CE]' WHERE id = 882;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 117.5 CE]' WHERE id = 873;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 119 CE]' WHERE id = 875;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 120.2 CE]' WHERE id = 876;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 125 CE]' WHERE id = 880;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 152.1 CE]' WHERE id = 881;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 64.1 CE]' WHERE id = 1144;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 149.1.20Âª CE]' WHERE id = 1228;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 151.2.2Âº CE]' WHERE id = 1230;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 148.1.11Âª CE]' WHERE id = 1231;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 124.4 CE]' WHERE id = 1209;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 124.2 CE]' WHERE id = 1153;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 148.1.19Âª CE]' WHERE id = 1233;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 138.1 CE]' WHERE id = 1383;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 15 Ley 50/1997]' WHERE id = 1376;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 121 CE establece que los daÃ±os causados por error judicial o por funcionamiento anormal de la AdministraciÃ³n de Justicia darÃ¡n derecho a indemnizaciÃ³n a cargo del Estado]' WHERE id = 438;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 122.3 CE establece que el CGPJ estarÃ¡ integrado por el Presidente del TS, que lo presidirÃ¡, y por veinte miembros nombrados por el Rey, a propuesta de Congreso y Senado]' WHERE id = 439;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 124.1 CE]' WHERE id = 823;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 117.5 CE]' WHERE id = 833;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 149.1 CE]' WHERE id = 1384;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 149.1 CE]' WHERE id = 1385;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 151.1 CE]' WHERE id = 1386;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 157.2 CE]' WHERE id = 1387;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 158.1 CE]' WHERE id = 1389;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 141.1 CE]' WHERE id = 1393;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 141.3 CE]' WHERE id = 1394;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 7 but cites law from Tema 5: Art. 141.4 CE]' WHERE id = 1395;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 8 but cites law from Tema 5: Art. 153 CE]' WHERE id = 223;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 8 but cites law from Tema 5: Art. 2 CE]' WHERE id = 219;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 8 but cites law from Tema 5: Art. 137 CE]' WHERE id = 220;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 8 but cites law from Tema 5: Art. 140 CE]' WHERE id = 221;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 8 but cites law from Tema 5: Art. 148.1.1Âª CE]' WHERE id = 222;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 8 but cites law from Tema 5: Art. 154 CE]' WHERE id = 936;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Tema 8 but cites law from Tema 5: Art. 154 CE]' WHERE id = 1340;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Duplicate of Q733 (93% similar)]' WHERE id = 762;
UPDATE questions SET needs_refresh = true, refresh_reason = '[DISCREPANCY: Duplicate of Q910 (95% similar)]' WHERE id = 753;

-- Total UPDATE statements: 104
